--CREATE TRIGGER nombre
--CUANDO ACTION[ES]
--AS
-- AQUI EL CODIGO

CREATE OR REPLACE FUNCTION name
RETURNS TRIGGER
AS
$BODY$ 
BEGIN
END;
$BODY$
LANGUAGE plpgsql;


CREATE TRIGGER nombre
BEFORE -- cuando BEFORE  or  AFTER
INSERT [OR UPDATE]-- acciones INSERT UPDATE DELETE
ON table_name
FOR EACH ROW EXECUTE PROCEDURE name_function;
